; ---------------------------------------------------------------------------
; FUSION FLIX — CLIP RENAMER & SORTER
; Custom NSIS fragments for the Windows installer.
;
; The app ships fully working WITHOUT FFmpeg (FFprobe is bundled and thumbnails
; are generated inside the app), but the optional engine adds background
; thumbnail extraction and the live sample generator. Instead of sending people
; to a website, the installer offers to fetch it right here, at install time.
;
; The download script is embedded below as a base64 PowerShell script and run
; with -EncodedCommand, so no quoting or escaping can go wrong; the install
; folder is passed as a plain argument.
; ---------------------------------------------------------------------------

!macro customHeader
  !system "echo Building the Fusion Flix Clip Renamer and Sorter installer"
!macroend

!define FF_ENGINE_PS "cABhAHIAYQBtACgAWwBQAGEAcgBhAG0AZQB0AGUAcgAoAE0AYQBuAGQAYQB0AG8AcgB5AD0AJAB0AHIAdQBlACkAXQBbAHMAdAByAGkAbgBnAF0AJABUAGEAcgBnAGUAdABEAGkAcgApAAoAJABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKAHQAcgB5ACAAewAgAFsATgBlAHQALgBTAGUAcgB2AGkAYwBlAFAAbwBpAG4AdABNAGEAbgBhAGcAZQByAF0AOgA6AFMAZQBjAHUAcgBpAHQAeQBQAHIAbwB0AG8AYwBvAGwAIAA9ACAAWwBOAGUAdAAuAFMAZQBjAHUAcgBpAHQAeQBQAHIAbwB0AG8AYwBvAGwAVAB5AHAAZQBdADoAOgBUAGwAcwAxADIAIAB9ACAAYwBhAHQAYwBoACAAewB9AAoAJAB1AHIAbABzACAAPQAgAEAAKAAKACAAIAAnAGgAdAB0AHAAcwA6AC8ALwB3AHcAdwAuAGcAeQBhAG4ALgBkAGUAdgAvAGYAZgBtAHAAZQBnAC8AYgB1AGkAbABkAHMALwBmAGYAbQBwAGUAZwAtAHIAZQBsAGUAYQBzAGUALQBlAHMAcwBlAG4AdABpAGEAbABzAC4AegBpAHAAJwAsAAoAIAAgACcAaAB0AHQAcABzADoALwAvAGcAaQB0AGgAdQBiAC4AYwBvAG0ALwBCAHQAYgBOAC8ARgBGAG0AcABlAGcALQBCAHUAaQBsAGQAcwAvAHIAZQBsAGUAYQBzAGUAcwAvAGQAbwB3AG4AbABvAGEAZAAvAGwAYQB0AGUAcwB0AC8AZgBmAG0AcABlAGcALQBtAGEAcwB0AGUAcgAtAGwAYQB0AGUAcwB0AC0AdwBpAG4ANgA0AC0AZwBwAGwALgB6AGkAcAAnAAoAKQAKACQAegBpAHAAIAAgAD0AIABKAG8AaQBuAC0AUABhAHQAaAAgACgAWwBJAE8ALgBQAGEAdABoAF0AOgA6AEcAZQB0AFQAZQBtAHAAUABhAHQAaAAoACkAKQAgACcAZgB1AHMAaQBvAG4ALQBmAGYAbQBwAGUAZwAuAHoAaQBwACcACgAkAGQAaQByACAAIAA9ACAASgBvAGkAbgAtAFAAYQB0AGgAIAAoAFsASQBPAC4AUABhAHQAaABdADoAOgBHAGUAdABUAGUAbQBwAFAAYQB0AGgAKAApACkAIAAnAGYAdQBzAGkAbwBuAC0AZgBmAG0AcABlAGcAJwAKACQAbwBrACAAPQAgACQAZgBhAGwAcwBlAAoAZgBvAHIAZQBhAGMAaAAgACgAJAB1ACAAaQBuACAAJAB1AHIAbABzACkAIAB7AAoAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBmAHUAcwBpAG8AbgAtAGYAbABpAHgAXQAgAGQAbwB3AG4AbABvAGEAZABpAG4AZwAgACQAdQAiAAoAIAAgACAAIABpAGYAIAAoAFQAZQBzAHQALQBQAGEAdABoACAAJAB6AGkAcAApACAAewAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgACQAegBpAHAAIAAtAEYAbwByAGMAZQAgAH0ACgAgACAAIAAgAEkAbgB2AG8AawBlAC0AVwBlAGIAUgBlAHEAdQBlAHMAdAAgAC0AVQByAGkAIAAkAHUAIAAtAE8AdQB0AEYAaQBsAGUAIAAkAHoAaQBwACAALQBVAHMAZQBCAGEAcwBpAGMAUABhAHIAcwBpAG4AZwAgAC0AVABpAG0AZQBvAHUAdABTAGUAYwAgADYAMAAwAAoAIAAgACAAIABpAGYAIAAoACgARwBlAHQALQBJAHQAZQBtACAAJAB6AGkAcAApAC4ATABlAG4AZwB0AGgAIAAtAGwAdAAgADEAMAAwADAAMAAwADAAKQAgAHsAIAB0AGgAcgBvAHcAIAAnAGQAbwB3AG4AbABvAGEAZAAgAHQAbwBvACAAcwBtAGEAbABsACcAIAB9AAoAIAAgACAAIABpAGYAIAAoAFQAZQBzAHQALQBQAGEAdABoACAAJABkAGkAcgApACAAewAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgACQAZABpAHIAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEYAbwByAGMAZQAgAH0ACgAgACAAIAAgAEUAeABwAGEAbgBkAC0AQQByAGMAaABpAHYAZQAgAC0AUABhAHQAaAAgACQAegBpAHAAIAAtAEQAZQBzAHQAaQBuAGEAdABpAG8AbgBQAGEAdABoACAAJABkAGkAcgAgAC0ARgBvAHIAYwBlAAoAIAAgACAAIAAkAG8AawAgAD0AIAAkAHQAcgB1AGUACgAgACAAIAAgAGIAcgBlAGEAawAKACAAIAB9ACAAYwBhAHQAYwBoACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBmAHUAcwBpAG8AbgAtAGYAbABpAHgAXQAgAHQAaABhAHQAIABtAGkAcgByAG8AcgAgAGQAaQBkACAAbgBvAHQAIAB3AG8AcgBrADoAIAAkACgAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBNAGUAcwBzAGEAZwBlACkAIgAKACAAIAB9AAoAfQAKAGkAZgAgACgALQBuAG8AdAAgACQAbwBrACkAIAB7ACAAdABoAHIAbwB3ACAAJwBlAHYAZQByAHkAIABkAG8AdwBuAGwAbwBhAGQAIABtAGkAcgByAG8AcgAgAGYAYQBpAGwAZQBkACcAIAB9AAoATgBlAHcALQBJAHQAZQBtACAALQBJAHQAZQBtAFQAeQBwAGUAIABEAGkAcgBlAGMAdABvAHIAeQAgAC0ARgBvAHIAYwBlACAALQBQAGEAdABoACAAJABUAGEAcgBnAGUAdABEAGkAcgAgAHwAIABPAHUAdAAtAE4AdQBsAGwACgAkAGkAbgBzAHQAYQBsAGwAZQBkACAAPQAgADAACgBmAG8AcgBlAGEAYwBoACAAKAAkAG4AYQBtAGUAIABpAG4AIABAACgAJwBmAGYAbQBwAGUAZwAuAGUAeABlACcALAAnAGYAZgBwAHIAbwBiAGUALgBlAHgAZQAnACkAKQAgAHsACgAgACAAJABmAG8AdQBuAGQAIAA9ACAARwBlAHQALQBDAGgAaQBsAGQASQB0AGUAbQAgAC0AUABhAHQAaAAgACQAZABpAHIAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEYAaQBsAHQAZQByACAAJABuAGEAbQBlACAALQBGAGkAbABlACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADEACgAgACAAaQBmACAAKAAkAGYAbwB1AG4AZAApACAAewAKACAAIAAgACAAQwBvAHAAeQAtAEkAdABlAG0AIAAkAGYAbwB1AG4AZAAuAEYAdQBsAGwATgBhAG0AZQAgACgASgBvAGkAbgAtAFAAYQB0AGgAIAAkAFQAYQByAGcAZQB0AEQAaQByACAAJABuAGEAbQBlACkAIAAtAEYAbwByAGMAZQAKACAAIAAgACAAJABpAG4AcwB0AGEAbABsAGUAZAAgAD0AIAAkAGkAbgBzAHQAYQBsAGwAZQBkACAAKwAgADEACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAZgB1AHMAaQBvAG4ALQBmAGwAaQB4AF0AIABpAG4AcwB0AGEAbABsAGUAZAAgACQAbgBhAG0AZQAiAAoAIAAgAH0AIABlAGwAcwBlACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBmAHUAcwBpAG8AbgAtAGYAbABpAHgAXQAgACQAbgBhAG0AZQAgAHcAYQBzACAAbgBvAHQAIABpAG4AIAB0AGgAZQAgAGEAcgBjAGgAaQB2AGUAIgAKACAAIAB9AAoAfQAKAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgACQAegBpAHAAIAAtAEYAbwByAGMAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAKAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgACQAZABpAHIAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEYAbwByAGMAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAKAGkAZgAgACgAJABpAG4AcwB0AGEAbABsAGUAZAAgAC0AbAB0ACAAMQApACAAewAgAHQAaAByAG8AdwAgACcAdABoAGUAIABhAHIAYwBoAGkAdgBlACAAZABpAGQAIABuAG8AdAAgAGMAbwBuAHQAYQBpAG4AIAB0AGgAZQAgAGUAbgBnAGkAbgBlACcAIAB9AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAWwBmAHUAcwBpAG8AbgAtAGYAbABpAHgAXQAgAG0AZQBkAGkAYQAgAGUAbgBnAGkAbgBlACAAcgBlAGEAZAB5ACcACgA="

; Registry breadcrumbs + the optional media-engine download.
!macro customInstall
  ; -------------------------------------------------------------------------
  ; Write the real uninstaller right here, at install time.
  ;
  ; electron-builder usually pre-builds "Uninstall Fusion Flix ... .exe" by
  ; running the installer under wine; without wine that step cannot run, so the
  ; custom script (packaging/installer.nsi) embeds a small placeholder which is
  ; replaced now with the genuine article generated from
  ; templates/nsis/uninstaller.nsh.  This is the classic NSIS pattern and needs
  ; nothing but the installer itself.
  ; -------------------------------------------------------------------------
  ClearErrors
  WriteUninstaller "$INSTDIR\${UNINSTALL_FILENAME}"
  IfErrors 0 +2
    DetailPrint "Warning: could not write $INSTDIR\${UNINSTALL_FILENAME}."

  WriteRegStr HKCU "Software\Fusion Flix\ClipRenamer" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "Software\Fusion Flix\ClipRenamer" "Version" "${VERSION}"

  IfSilent ffxEngineDone
  IfFileExists "$INSTDIR\resources\app.asar" 0 ffxEngineDone

  MessageBox MB_YESNO|MB_ICONQUESTION \
    "Download the media engine (FFmpeg) now?$\r$\n$\r$\n\
     Recommended: it is what lets Fusion Flix PREVIEW and thumbnail camera$\r$\n\
     footage. HEVC/H.265, ProRes and 10-bit clips cannot be decoded by a$\r$\n\
     normal video player component, so without the engine the app can only$\r$\n\
     show them as a still frame.$\r$\n$\r$\n\
     Roughly 60-110 MB from the official FFmpeg mirrors, one time, needs an$\r$\n\
     internet connection and takes a minute or two.$\r$\n$\r$\n\
     FFprobe (clip durations, resolution, frame rate, source timecode) is$\r$\n\
     already bundled and works offline either way.$\r$\n\
     You can also add the engine later from Settings > Media engine." \
    /SD IDNO IDNO ffxEngineDone

  DetailPrint "Downloading the optional media engine (FFmpeg)..."
  nsExec::ExecToLog 'powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand ${FF_ENGINE_PS} "$INSTDIR\resources\ffmpeg"'
  Pop $0
  DetailPrint "Media engine step finished (exit code $0)."

  ffxEngineDone:
!macroend

!macro customUnInstall
  DeleteRegKey HKCU "Software\Fusion Flix\ClipRenamer"
!macroend
